#!/bin/bash

RELEASE="00.00.01"

TXT_FILE="current_test_firmware.txt"
BIN_FILE_PATH="build/tixclock.bin"
SERVER="forsyth@www.dforsyth.net"
BASE_PATH="/home/httpd/html_2dkits/kits/kit99"


echo "$RELEASE kits/kit99/blaster_test_$RELEASE.bin" > $TXT_FILE
echo "$RELEASE"

scp $TXT_FILE      $SERVER:$BASE_PATH/$TXT_FILE
scp $BIN_FILE_PATH $SERVER:$BASE_PATH/blaster_test_$RELEASE.bin

ssh $SERVER "mkdir -p $BASE_PATH/${RELEASE}_test"
for FILE_NAME in index.html header.html footer.html about.html settings.html patterns.html content-bg.jpg styles.css header-bg.jpg box-title-bg.jpg
do
    scp -pr disk_image/$FILE_NAME $SERVER:$BASE_PATH/${RELEASE}_test/$FILE_NAME
done
