#!/bin/bash

RELEASE="00.00.01"

TXT_FILE="current_firmware.txt"
BIN_FILE_PATH="build/tower.bin"

echo "$RELEASE kits/kit25/tower_$RELEASE.bin" > $TXT_FILE
echo "$RELEASE"

scp $TXT_FILE      forsyth@www.dforsyth.net:/home/httpd/html_2dkits/kits/kit25/$TXT_FILE
scp $BIN_FILE_PATH forsyth@www.dforsyth.net:/home/httpd/html_2dkits/kits/kit25/tower_$RELEASE.bin

