#!/bin/bash

RELEASE="00.01.03"

TXT_FILE="current_test_firmware.txt"
BIN_FILE_PATH="build/tower.bin"
SERVER="forsyth@www.dforsyth.net"
BASE_PATH="/home/httpd/html_2dkits/kits/kit25"

echo "$RELEASE kits/kit25/tower_test_$RELEASE.bin" > $TXT_FILE
echo "$RELEASE"

scp $TXT_FILE      $SERVER:$BASE_PATH/$TXT_FILE
scp $BIN_FILE_PATH $SERVER:$BASE_PATH/tower_test_$RELEASE.bin

ssh $SERVER "mkdir -p $BASE_PATH/${RELEASE}_test"
for FILE_NAME in index.html header.html footer.html about.html settings.html patterns.html content-bg.jpg styles.css header-bg.jpg box-title-bg.jpg
do
    scp -pr disk_image/$FILE_NAME $SERVER:$BASE_PATH/${RELEASE}_test/$FILE_NAME
done

scp patterns/*.pat $SERVER:$BASE_PATH/patterns

