# This is a basic workflow to help you get started with Actions

name: Test on Hardware - tower

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ESP32]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.KEY }}
      # setup the needed toolchain
      - name: setup tool chain
        run:
          esp-idf/install.sh

      # build
      - name: build
        run: |
          . esp-idf/export.sh
          cd tower
          idf.py build

      # Flash
      - name: flash via default tty
        run: |
          . esp-idf/export.sh
          cd tower
          idf.py flash

      # test - connect console
      - name: test connect consle, get version
        run: |
          . esp-idf/export.sh
          cd test/tower.proj
          chmod a+x test_001.py
          ./test_001.py

      # test - connect wifi
      - name: test wifi connect
        run: |
          . esp-idf/export.sh
          cd test/tower.proj
          chmod a+x test_002.py
          ./test_002.py
